---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-two
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sb-campbell/cicd-argocd-gitops-demo.git
    targetRevision: HEAD
    path: example2-argocd-app-of-apps/environments/stage/my-app-two
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
